//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.26 at 05:01:48 PM CET 
//


package xml.web.services.team2.sciXiv.model.businessProcess;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scientificPublicationTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="processState" type="{http://ftn.uns.ac.rs/businessProcess}TProcessStateEnum"/>
 *         &lt;element name="reviewerAssignments">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="reviewerAssignment" type="{http://ftn.uns.ac.rs/businessProcess}TReviewerAssignment" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "scientificPublicationTitle",
    "version",
    "processState",
    "reviewerAssignments"
})
@XmlRootElement(name = "businessProcess")
public class BusinessProcess {

    @XmlElement(required = true)
    protected String scientificPublicationTitle;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger version;
    @XmlElement(required = true)
    protected TProcessStateEnum processState;
    @XmlElement(required = true)
    protected BusinessProcess.ReviewerAssignments reviewerAssignments;

    /**
     * Gets the value of the scientificPublicationTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScientificPublicationTitle() {
        return scientificPublicationTitle;
    }

    /**
     * Sets the value of the scientificPublicationTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScientificPublicationTitle(String value) {
        this.scientificPublicationTitle = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersion(BigInteger value) {
        this.version = value;
    }

    /**
     * Gets the value of the processState property.
     * 
     * @return
     *     possible object is
     *     {@link TProcessStateEnum }
     *     
     */
    public TProcessStateEnum getProcessState() {
        return processState;
    }

    /**
     * Sets the value of the processState property.
     * 
     * @param value
     *     allowed object is
     *     {@link TProcessStateEnum }
     *     
     */
    public void setProcessState(TProcessStateEnum value) {
        this.processState = value;
    }

    /**
     * Gets the value of the reviewerAssignments property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessProcess.ReviewerAssignments }
     *     
     */
    public BusinessProcess.ReviewerAssignments getReviewerAssignments() {
        return reviewerAssignments;
    }

    /**
     * Sets the value of the reviewerAssignments property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessProcess.ReviewerAssignments }
     *     
     */
    public void setReviewerAssignments(BusinessProcess.ReviewerAssignments value) {
        this.reviewerAssignments = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="reviewerAssignment" type="{http://ftn.uns.ac.rs/businessProcess}TReviewerAssignment" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "reviewerAssignment"
    })
    public static class ReviewerAssignments {

        protected List<TReviewerAssignment> reviewerAssignment;

        /**
         * Gets the value of the reviewerAssignment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the reviewerAssignment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getReviewerAssignment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TReviewerAssignment }
         * 
         * 
         */
        public List<TReviewerAssignment> getReviewerAssignment() {
            if (reviewerAssignment == null) {
                reviewerAssignment = new ArrayList<TReviewerAssignment>();
            }
            return this.reviewerAssignment;
        }

    }

}
