//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.26 at 05:01:48 PM CET 
//


package xml.web.services.team2.sciXiv.model.businessProcess;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TProcessStateEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TProcessStateEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="published"/>
 *     &lt;enumeration value="rejected"/>
 *     &lt;enumeration value="withdrawn"/>
 *     &lt;enumeration value="on_review"/>
 *     &lt;enumeration value="on_revision"/>
 *     &lt;enumeration value="submitted"/>
 *     &lt;enumeration value="revised"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TProcessStateEnum")
@XmlEnum
public enum TProcessStateEnum {

    @XmlEnumValue("published")
    PUBLISHED("published"),
    @XmlEnumValue("rejected")
    REJECTED("rejected"),
    @XmlEnumValue("withdrawn")
    WITHDRAWN("withdrawn"),
    @XmlEnumValue("on_review")
    ON_REVIEW("on_review"),
    @XmlEnumValue("on_revision")
    ON_REVISION("on_revision"),
    @XmlEnumValue("submitted")
    SUBMITTED("submitted"),
    @XmlEnumValue("revised")
    REVISED("revised");
    private final String value;

    TProcessStateEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TProcessStateEnum fromValue(String v) {
        for (TProcessStateEnum c: TProcessStateEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
