//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.26 at 05:01:48 PM CET 
//


package xml.web.services.team2.sciXiv.model.businessProcess;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TReviewerAssignment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TReviewerAssignment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reviewerEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="status" type="{http://ftn.uns.ac.rs/businessProcess}TReviewStatus"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TReviewerAssignment", propOrder = {
    "reviewerEmail",
    "status"
})
public class TReviewerAssignment {

    @XmlElement(required = true)
    protected String reviewerEmail;
    @XmlElement(required = true)
    protected TReviewStatus status;

    /**
     * Gets the value of the reviewerEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewerEmail() {
        return reviewerEmail;
    }

    /**
     * Sets the value of the reviewerEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewerEmail(String value) {
        this.reviewerEmail = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link TReviewStatus }
     *     
     */
    public TReviewStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link TReviewStatus }
     *     
     */
    public void setStatus(TReviewStatus value) {
        this.status = value;
    }

}
